### PR TITLE
Save State Pages

### PR DESCRIPTION
**Pull request by jhearom**
Added paged save state functionality - basing off of code in the cerpintext/debugmod repo, 1.2.2.1 branch. Threw in some code touch-ups on the way.

### CODE REVIEW

**Comment by Ruttie2006** [comment]
AAAaah it seems like mulhima missedy you!
Dw, I shall now annoy him everyday to look at this pr again so he doesn't forget!

**Comment by TheMulhima** [comment]
I'll just test this once and merge
Sorry for taking so long

**Comment by Ruttie2006** [comment]
imagine being slow :maggotprime:

**Comment by jhearom** [comment]
Ha no worries. This is more of a thing I did for me but figured if I can upstream it so that others can have it, it'd be nice. The Scarab mod installer reaches out for this particular repo's releases. Not sure about others.

**Pull request merged**
